export const GET_TRACKS = 'GET_TRACKS';
export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS';
export const GET_TRACKS_FAIL = 'GET_TRACKS_FAIL';

export const POST_TRACK = 'POST_TRACK';
export const POST_TRACK_SUCCESS = 'POST_TRACK_SUCCESS';
export const POST_TRACK_FAIL = 'POST_TRACK_FAIL';
